import unittest
import os
import uuid
import tempfile
from skills.system_health_monitoring_gateway import SystemHealthMonitoringGateway

class TestSystemHealthMonitoringGatewayIntegration(unittest.TestCase):
    def setUp(self):
        self.gateway = SystemHealthMonitoringGateway()
        self.test_dir = tempfile.TemporaryDirectory()
        
        self.random_module_name = f"module_{uuid.uuid4().hex[:8]}"
        self.random_incident_id = str(uuid.uuid4())
        self.random_summary = f"Audit summary {uuid.uuid4().hex[:6]}"
        self.random_metric_value = float(uuid.uuid4().int % 100)
        
        self.incident_data = {
            "incident_id": self.random_incident_id,
            "severity": "HIGH",
            "description": "Integration test incident"
        }
        self.audit_summary = {
            "summary": self.random_summary,
            "status": "PASSED"
        }
        self.metrics = {
            "cpu_usage": self.random_metric_value,
            "memory_usage": 45.2
        }
        self.dashboard_format = "json"
        self.incidents_list = [self.incident_data]
        self.patches_list = [{"patch_id": str(uuid.uuid4()), "status": "APPLIED"}]
        
        self.report_path = os.path.join(self.test_dir.name, f"report_{uuid.uuid4().hex[:8]}.json")
        self.dashboard_path = os.path.join(self.test_dir.name, f"dashboard_{uuid.uuid4().hex[:8]}.json")

    def tearDown(self):
        self.test_dir.cleanup()

    def test_end_to_end_health_monitoring_gateway_pipeline(self):
        result = self.gateway.execute_monitoring_and_reporting_pipeline(
            module_name=self.random_module_name,
            incident_data=self.incident_data,
            audit_summary=self.audit_summary,
            metrics=self.metrics,
            dashboard_format=self.dashboard_format,
            incidents_list=self.incidents_list,
            patches_list=self.patches_list,
            report_path=self.report_path,
            dashboard_path=self.dashboard_path
        )

        self.assertIsInstance(result, dict)
        self.assertIn("audit_pipeline_result", result)
        self.assertIn("health_report", result)

        report_data = result["health_report"]
        self.assertEqual(report_data.get("module_name"), self.random_module_name)
        self.assertEqual(report_data.get("audit_summary"), self.audit_summary)

        self.assertTrue(os.path.exists(self.report_path), "Report file must be generated by the integrated pipeline.")
        self.assertTrue(os.path.exists(self.dashboard_path), "Dashboard file must be generated by the integrated pipeline.")

        with open(self.report_path, "r", encoding="utf-8") as f:
            file_content = f.read()
            self.assertIn(self.random_module_name, file_content)

if __name__ == "__main__":
    unittest.main()