import unittest
import uuid
import random
import sys
import os

from skills.patch_validator import PatchValidator
from error_recovery_hub import ErrorRecoveryHub

class TestPatchValidatorIntegration(unittest.TestCase):
    def setUp(self):
        self.validator = PatchValidator()
        self.hub = ErrorRecoveryHub()
        self.random_module_name = f"test_module_{uuid.uuid4().hex[:8]}"
        self.random_error_msg = f"RandomError_{uuid.uuid4().hex[:6]}"
        self.random_exception = RuntimeError(self.random_error_msg)
        self.random_traceback = f"Traceback (most recent call last):\n  File '{self.random_module_name}.py', line {random.randint(1, 100)}, in <module>\n    raise {self.random_error_msg}"

    def test_patch_validation_end_to_end_integration(self):
        incident_id = self.hub.capture_failure(
            module_name=self.random_module_name,
            exception=self.random_exception,
            traceback_str=self.random_traceback
        )
        self.assertIsNotNone(incident_id)

        analysis_result = self.hub.analyze_failure(incident_id)
        self.assertIsNotNone(analysis_result)

        patch_data = self.hub.generate_patch(incident_id)
        self.assertIsNotNone(patch_data)

        validation_result = self.validator.validate(patch_data)
        self.assertTrue(validation_result, "PatchValidator rejected a valid patch generated by ErrorRecoveryHub")

        apply_result = self.hub.apply_patch(patch_data)
        self.assertTrue(apply_result)

        verification_result = self.hub.deploy_and_verify(incident_id, patch_data)
        self.assertTrue(verification_result)

        history = self.hub.get_incident_history(self.random_module_name)
        self.assertIsInstance(history, list)
        self.assertGreater(len(history), 0)

        logs = self.hub.get_incident_logs(incident_id)
        self.assertIsNotNone(logs)

if __name__ == '__main__':
    unittest.main()