import os
import requests

from skills.db_storage import db_storage
from skills.extractor_tool_1790087207 import extractor_tool_1790087207
from skills.extractor_tool_1790102839 import extractor_tool_1790102839
from skills.extractor_tool_1790262909 import extractor_tool_1790262909
from skills.extractor_tool_1790621808 import extractor_tool_1790621808
from skills.market_anomaly_detector import market_anomaly_detector
from skills.market_insider_activity_tracker import market_insider_activity_tracker
from skills.market_insider_alert_pipeline import market_insider_alert_pipeline
from skills.market_insider_anomaly_analyzer import market_insider_anomaly_analyzer
from skills.market_insider_anomaly_report_bridge import market_insider_anomaly_report_bridge
from skills.market_news_sentiment_analyzer import market_news_sentiment_analyzer
from skills.market_parser import market_parser
from skills.market_portfolio_alert_dispatcher import market_portfolio_alert_dispatcher
from skills.market_portfolio_alert_event_sink import market_portfolio_alert_event_sink
from skills.market_portfolio_alert_filter_router import market_portfolio_alert_filter_router
from skills.market_portfolio_api_gateway import market_portfolio_api_gateway
from skills.market_portfolio_audit_alert_notifier import market_portfolio_audit_alert_notifier
from skills.market_portfolio_audit_compliance_hub import market_portfolio_audit_compliance_hub
from skills.market_portfolio_audit_log_exporter import market_portfolio_audit_log_exporter
from skills.market_portfolio_autonomous_sentinel import market_portfolio_autonomous_sentinel
from skills.market_portfolio_backtest_evaluator_bridge import market_portfolio_backtest_evaluator_bridge
from skills.market_portfolio_backtester import market_portfolio_backtester
from skills.market_portfolio_collector_agent import market_portfolio_collector_agent
from skills.market_portfolio_data_exporter import market_portfolio_data_exporter
from skills.market_portfolio_digest import market_portfolio_digest
from skills.market_portfolio_dividend_tracker import market_portfolio_dividend_tracker
from skills.market_portfolio_event_intelligence_hub import market_portfolio_event_intelligence_hub
from skills.market_portfolio_execution_cost_optimizer import market_portfolio_execution_cost_optimizer
from skills.market_portfolio_execution_pipeline import market_portfolio_execution_pipeline
from skills.market_portfolio_integration_hub import market_portfolio_integration_hub
from skills.market_portfolio_liquidity_scenario_analyzer import market_portfolio_liquidity_scenario_analyzer
from skills.market_portfolio_monitor import market_portfolio_monitor
from skills.market_portfolio_performance_analytics import market_portfolio_performance_analytics
from skills.market_portfolio_predictive_aggregator import market_portfolio_predictive_aggregator
from skills.market_portfolio_scenario_simulator import market_portfolio_scenario_simulator
from skills.market_portfolio_slippage_model import market_portfolio_slippage_model
from skills.market_portfolio_strategy_optimizer import market_portfolio_strategy_optimizer
from skills.market_portfolio_stress_audit_visualizer import market_portfolio_stress_audit_visualizer
from skills.market_portfolio_stress_monte_carlo_engine import market_portfolio_stress_monte_carlo_engine
from skills.market_portfolio_stress_recovery_coordinator_bridge import market_portfolio_stress_recovery_coordinator_bridge
from skills.market_portfolio_stress_reporter import market_portfolio_stress_reporter
from skills.market_portfolio_stress_scenario_pipeline import market_portfolio_stress_scenario_pipeline
from skills.market_portfolio_tax_calculator import market_portfolio_tax_calculator
from skills.market_portfolio_telegram_command_center import market_portfolio_telegram_command_center
from skills.market_portfolio_telegram_notifier import market_portfolio_telegram_notifier
from skills.market_portfolio_valuation import market_portfolio_valuation
from skills.market_portfolio_var_liquidity_core import market_portfolio_var_liquidity_core
from skills.market_portfolio_visualizer_v2 import market_portfolio_visualizer_v2
from skills.market_portfolio_webhook_event_logger import market_portfolio_webhook_event_logger
from skills.market_portfolio_webhook_sync import market_portfolio_webhook_sync
from skills.market_report_generator import market_report_generator
from skills.market_sentiment_digest import market_sentiment_digest
from skills.market_sentiment_risk_alert_bridge import market_sentiment_risk_alert_bridge
from skills.market_sentiment_risk_hub import market_sentiment_risk_hub
from skills.market_sentiment_telegram_publisher import market_sentiment_telegram_publisher
from skills.market_telegram_pipeline import market_telegram_pipeline

def start_new(*args, **kwargs):
    response = requests.get("https://market.internal/api/v2/macro")
    response.raise_for_status()
    data = response.json()
    
    detector = kwargs.get("market_anomaly_detector")
    if detector and hasattr(detector, "evaluate"):
        detector.evaluate()
        
    return data